### ISSUE TITLE
Why did you only consider BUY orders when calculating the VWAP?

### ISSUE THREAD

**Issue by mbucko** [yuejin123/NASDAQ_ITCH_Running_VWAP_Calculater#2]

**Comment by shashwatmaiti24** [comment]
Consider the following set of messages:
1. Buy order: share = AAPL, price = 180, quantity = 10, order_number = 123
2. Sell order: share = AAPL, price = 180, quantity = 10, order_number = 456
3. Order execution: order_number = 123
4. Order execution: order_number = 456

If you consider both you will count the same trade twice.
